AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  # Detection
  DetectionSchedule:
    Type: String
    Description: Schedule Expression to trigger the drift detection. Default every 15 min from 6 AM to 7 AM.
    Default: cron(0/15 6 ? * * *)
  DriftAgeCheckHours:
    Type: Number
    Description: Minimum time after the last drift detection to trigger a new drift detection.
    MinValue: 0
    Default: 23
  # Notifier
  NotificationSchedule:
    Type: String
    Description: Schedule Expression to trigger the drift notification. Default 1h after last detection.
    Default: cron(45 7 ? * * *)
  NotifierService:
    Type: String
    AllowedValues:
      - SES
      - SNS
    Description: >
      Service used to notify drifts.
      Prefer SES for prettier HTML table render.
      SNS render non formatted text email.
  NotifierRegion:
    Type: String
    Description: Region where the notifier (SES identity or SNS topic) is deployed
  Destination:
    Type: String
    Description: >
      Destination email to send the drift notification.
      For SES notifier, ensure this email is verified in sandboxed SES.
      For SNS notifier, ensure this email is subscribed before the notifier runs.
  SesSource:
    Type: String
    Description: SES source email
    Default: ""
  # Global
  Regions:
    Type: String
    Description: Comma-separated list of regions to scan for CloudFormation stacks, e.g. eu-west-3,us-west-1.
  IgnoreStackIdRegex:
    Type: String
    Description: Regex to ignore stacks by id. Applies to StackId and RootId for a stack.
  Tracing:
    Type: String
    Description: XRAY tracing mode. Set to Active to enable XRAY.
    AllowedValues:
      - Active
      - PassThrough

Conditions:
  IsSES: !Equals [!Ref NotifierService, SES]
  IsSNS: !Equals [!Ref NotifierService, SNS]

Globals:
  Function:
    Runtime: nodejs18.x
    MemorySize: 128
    # For ~1000 stacks it takes ~10 minutes
    Timeout: 900 # 15 minutes
    Tracing: !Ref Tracing
    Layers:
      - !Ref NodeModulesLayer

Resources:
  NodeModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${AWS::StackName}-NodeModulesLayer
      Description: node modules
      ContentUri: ../dist/layer
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Delete
      LicenseInfo: https://unlicense.org/

  DetectStackDrifts:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: ../dist/detect-stack-drifts
      Environment:
        Variables:
          XRAY_TRACING: !Ref Tracing
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: !Ref DetectionSchedule
            # ScheduleExpression: !Ref DetectionSchedule
            # ScheduleExpressionTimezone: !Ref DetectionScheduleTimezone
            RetryPolicy:
              MaximumRetryAttempts: 10
              MaximumEventAgeInSeconds: 3600 # 1 hour
            Input: !Sub >-
              {
                "REGIONS": "${Regions}",
                "DRIFT_AGE_CHECK_HOURS": "${DriftAgeCheckHours}",
                "IGNORE_STACK_ID_REGEX": "${IgnoreStackIdRegex}"
              }
      Policies:
        - ReadOnlyAccess

  NotifierTopic:
    Type: AWS::SNS::Topic
    Condition: IsSNS
    Properties:
      Subscription:
        - Protocol: email
          Endpoint: !Ref Destination

  NotifyStackDrifts:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: ../dist/notify
      Environment:
        Variables:
          XRAY_TRACING: !Ref Tracing
          TOPIC_ARN: !If [IsSNS, !Ref NotifierTopic, ""]
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: !Ref NotificationSchedule
            # ScheduleExpression: !Ref NotificationSchedule
            # ScheduleExpressionTimezone: !Ref DetectionScheduleTimezone
            RetryPolicy:
              MaximumRetryAttempts: 10
              MaximumEventAgeInSeconds: 3600 # 1 hour
            Input: !Sub >-
              {
                "REGIONS": "${Regions}",
                "IGNORE_STACK_ID_REGEX": "${IgnoreStackIdRegex}",
                "NOTIFIER_REGION": "${NotifierRegion}",
                "DESTINATION": "${Destination}",
                "SES_SOURCE": "${SesSource}"
              }
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - cloudformation:ListStacks
                - cloudformation:DescribeStackResourceDrifts
              Resource: "*"
        - !If
          - IsSES
          - SESCrudPolicy:
              IdentityName: !Ref SesSource
          - SNSPublishMessagePolicy:
              TopicName: !GetAtt NotifierTopic.TopicName
