AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  DetectionSchedule:
    Type: String
    Description: Schedule Expression to trigger the drift detection. Default everyday at noon.
    Default: cron(0 12 ? * * *)
  DetectionScheduleTimezone:
    Type: String
    Description: Timezone for the detection schedule expression.
    Default: UTC
  Regions:
    Type: String
    Description: Comma-separated list of regions to scan for CloudFormation stacks, e.g. eu-west-3,us-west-1.
  DriftAgeCheckHours:
    Type: Number
    Description: Minimum time after the last drift detection to trigger a new drift detection.
    MinValue: 0
    Default: 23
  IgnoreStackIdRegex:
    Type: String
    Description: Regex to ignore stacks by id. Applies to StackId and RootId for a stack.

Globals:
  Function:
    Runtime: nodejs18.x
    MemorySize: 256
    Timeout: 300 # 5 minutes
    Tracing: Active
    Layers:
      - !Ref NodeModulesLayer

Resources:
  NodeModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${AWS::StackName}-NodeModulesLayer
      Description: node modules
      ContentUri: ../dist/layer
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Delete
      LicenseInfo: https://unlicense.org/

  DetectStackDrifts:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: ../dist/detect-stack-drifts
      Events:
        ScheduleEvent:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: !Ref DetectionSchedule
            ScheduleExpressionTimezone: !Ref DetectionScheduleTimezone
            RetryPolicy:
              MaximumRetryAttempts: 10
              MaximumEventAgeInSeconds: 3600 # 1 hour
            Input: !Sub >-
              {
                "REGIONS": "${Regions}",
                "DRIFT_AGE_CHECK_HOURS": "${DriftAgeCheckHours}",
                "IGNORE_STACK_ID_REGEX": "${IgnoreStackIdRegex}"
              }
      Policies:
        - ReadOnlyAccess
